"""Foto de capa obrigatória

Revision ID: ccfe12ed2dec
Revises: aff041ba4948
Create Date: 2024-09-09 21:32:18.014201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccfe12ed2dec'
down_revision = 'aff041ba4948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('foto_cover',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('foto_cover',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
