"""Novas tabelas relacionamento

Revision ID: 39e20ef0e948
Revises: b53cd7300527
Create Date: 2024-07-13 15:28:19.538859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39e20ef0e948'
down_revision = 'b53cd7300527'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario_post_nota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('estrelas', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentario_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('comentario_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_report', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['comentario_id'], ['comentarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conteudo', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('nota_geral', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ultima_atualizacao', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('editado', sa.Boolean(), nullable=True))
        batch_op.drop_column('texto')
        batch_op.drop_column('media_estrelas')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('categoria')

    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_estrelas', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('texto', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('editado')
        batch_op.drop_column('ultima_atualizacao')
        batch_op.drop_column('nota_geral')
        batch_op.drop_column('conteudo')

    op.drop_table('comentario_reports')
    op.drop_table('usuario_post_nota')
    # ### end Alembic commands ###
